/* global ol, shp */
const APP_KEY = "notatkart:data:v1";
const PHOTO_DB = "notatkart-photos";
const PHOTO_STORE = "photos";
const projection = "EPSG:3857";
const $ = (id) => document.getElementById(id);
const drawingSource = new ol.source.Vector();
const notesSource = new ol.source.Vector();
const importSource = new ol.source.Vector();
const positionSource = new ol.source.Vector();
const format = new ol.format.GeoJSON();
let drawInteraction;
let toolMode = null;
let selectedFeature = null;
let pendingPhoto = null;
let pendingSymbol = null;
let positionWatch;
let toastTimer;

function uid() { return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`; }
function toast(message) { const el = $("toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove("show"), 3600); }
function localFeatureStyle(feature) {
  const type = feature.get("noteType");
  if (type === "symbol") {
    const symbolType = feature.get("symbolType");
    const styles = {
      culvert: new ol.style.Style({ image: new ol.style.RegularShape({ points: 4, radius: 11, angle: Math.PI / 4, fill: new ol.style.Fill({ color: "#3a7cbb" }), stroke: new ol.style.Stroke({ color: "#fff", width: 2 }) }), text: new ol.style.Text({ text: `Ø ${feature.get("diameter")} mm`, offsetY: -20, font: "800 13px system-ui", fill: new ol.style.Fill({ color: "#17302a" }), stroke: new ol.style.Stroke({ color: "#fff", width: 3 }) }) }),
      landing: new ol.style.Style({ image: new ol.style.RegularShape({ points: 3, radius: 13, rotation: 0, fill: new ol.style.Fill({ color: "#dc6f45" }), stroke: new ol.style.Stroke({ color: "#fff", width: 2 }) }), text: new ol.style.Text({ text: "Velteplass", offsetY: -22, font: "800 12px system-ui", fill: new ol.style.Fill({ color: "#17302a" }), stroke: new ol.style.Stroke({ color: "#fff", width: 3 }) }) }),
      turning: new ol.style.Style({ image: new ol.style.Circle({ radius: 12, fill: new ol.style.Fill({ color: "#7a5aa6" }), stroke: new ol.style.Stroke({ color: "#fff", width: 2 }) }), text: new ol.style.Text({ text: "S", font: "800 13px system-ui", fill: new ol.style.Fill({ color: "#fff" }), textAlign: "center", textBaseline: "middle" }) })
    };
    return styles[symbolType];
  }
  if (type === "text") return new ol.style.Style({ image: new ol.style.Circle({ radius: 9, fill: new ol.style.Fill({ color: "#dc6f45" }), stroke: new ol.style.Stroke({ color: "#fff", width: 2 }) }), text: new ol.style.Text({ text: feature.get("title") || "Notat", offsetY: -19, font: "700 13px system-ui", fill: new ol.style.Fill({ color: "#17302a" }), stroke: new ol.style.Stroke({ color: "#fff", width: 3 }) }) });
  if (type === "photo") return new ol.style.Style({ image: new ol.style.RegularShape({ points: 4, radius: 12, angle: Math.PI / 4, fill: new ol.style.Fill({ color: "#1e4d3a" }), stroke: new ol.style.Stroke({ color: "#fff", width: 2 }) }), text: new ol.style.Text({ text: "Bilde", offsetY: -21, font: "700 12px system-ui", fill: new ol.style.Fill({ color: "#17302a" }), stroke: new ol.style.Stroke({ color: "#fff", width: 3 }) }) });
  const geometryType = feature.getGeometry().getType();
  return new ol.style.Style({ fill: geometryType === "Polygon" ? new ol.style.Fill({ color: "rgba(220,111,69,.18)" }) : undefined, stroke: new ol.style.Stroke({ color: "#dc6f45", width: 4, lineCap: "round", lineJoin: "round" }), image: new ol.style.Circle({ radius: 5, fill: new ol.style.Fill({ color: "#dc6f45" }) }) });
}
function importedStyle() { return new ol.style.Style({ fill: new ol.style.Fill({ color: "rgba(49,115,86,.13)" }), stroke: new ol.style.Stroke({ color: "#317356", width: 2 }), image: new ol.style.Circle({ radius: 4, fill: new ol.style.Fill({ color: "#317356" }) }) }); }
const baseLayer = new ol.layer.Tile({ source: new ol.source.TileWMS({ url: "https://wms.geonorge.no/skwms1/wms.norges_grunnkart", params: { LAYERS: "Norges_grunnkart", FORMAT: "image/png", TRANSPARENT: false }, crossOrigin: "anonymous" }) });
const importLayer = new ol.layer.Vector({ source: importSource, style: importedStyle });
const notesLayer = new ol.layer.Vector({ source: notesSource, style: localFeatureStyle });
const drawingLayer = new ol.layer.Vector({ source: drawingSource, style: localFeatureStyle });
const positionLayer = new ol.layer.Vector({ source: positionSource, style: new ol.style.Style({ image: new ol.style.Circle({ radius: 8, fill: new ol.style.Fill({ color: "#2877d5" }), stroke: new ol.style.Stroke({ color: "#fff", width: 3 }) }) }) });
const map = new ol.Map({ target: "map", layers: [baseLayer, importLayer, drawingLayer, notesLayer, positionLayer], view: new ol.View({ center: ol.proj.fromLonLat([10.256, 60.168]), zoom: 8, maxZoom: 20 }), controls: ol.control.defaults.defaults({ attribution: false }) });

function countObjects() { $("import-count").textContent = `${importSource.getFeatures().length} objekt${importSource.getFeatures().length === 1 ? "" : "er"}`; $("note-count").textContent = `${drawingSource.getFeatures().length + notesSource.getFeatures().length} objekt${drawingSource.getFeatures().length + notesSource.getFeatures().length === 1 ? "" : "er"}`; }
function serialise(source) { return format.writeFeaturesObject(source.getFeatures(), { featureProjection: projection, dataProjection: projection }); }
function readInto(source, data) { if (data?.features) source.addFeatures(format.readFeatures(data, { featureProjection: projection, dataProjection: projection })); }
function saveData() { localStorage.setItem(APP_KEY, JSON.stringify({ drawings: serialise(drawingSource), notes: serialise(notesSource), imports: serialise(importSource) })); countObjects(); }
function loadData() { try { const data = JSON.parse(localStorage.getItem(APP_KEY)); if (data) { readInto(drawingSource, data.drawings); readInto(notesSource, data.notes); readInto(importSource, data.imports); } } catch { toast("Kunne ikke lese tidligere lokale notater."); } countObjects(); }
function photoDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(PHOTO_DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(PHOTO_STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function savePhoto(id, blob) { const db = await photoDatabase(); return new Promise((resolve, reject) => { const tx = db.transaction(PHOTO_STORE, "readwrite"); tx.objectStore(PHOTO_STORE).put(blob, id); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
async function getPhoto(id) { const db = await photoDatabase(); return new Promise((resolve, reject) => { const request = db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(id); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function deletePhoto(id) { const db = await photoDatabase(); return new Promise((resolve, reject) => { const tx = db.transaction(PHOTO_STORE, "readwrite"); tx.objectStore(PHOTO_STORE).delete(id); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); }
function deactivateTool() { if (drawInteraction) { map.removeInteraction(drawInteraction); drawInteraction = null; } toolMode = null; document.querySelectorAll("[data-draw]").forEach((button) => button.classList.remove("active")); $("map").style.cursor = ""; }
function activateDraw(kind) { deactivateTool(); toolMode = "draw"; document.querySelector(`[data-draw="${kind}"]`).classList.add("active"); drawInteraction = new ol.interaction.Draw({ source: drawingSource, type: kind === "freehand" ? "LineString" : kind, freehand: kind === "freehand", style: new ol.style.Style({ stroke: new ol.style.Stroke({ color: "#dc6f45", width: 4 }) }) }); drawInteraction.on("drawend", (event) => { event.feature.setProperties({ id: uid(), noteType: "sketch", createdAt: new Date().toISOString() }); saveData(); toast("Skissen er lagret lokalt på denne enheten."); deactivateTool(); }); map.addInteraction(drawInteraction); toast(kind === "Polygon" ? "Tegn område og dobbelttrykk for å avslutte." : "Tegn i kartet. Dobbelttrykk for å avslutte."); }
function selectPlacement(kind) { deactivateTool(); toolMode = kind; $("map").style.cursor = "crosshair"; const messages = { text: "Trykk i kartet der tekstboksen skal plasseres.", photo: "Trykk i kartet der bildet hører til.", symbol: `Trykk i kartet der ${pendingSymbol?.label?.toLowerCase() || "symbolet"} skal plasseres.` }; toast(messages[kind]); }
async function addPhoto(coordinate) { const id = uid(); try { await savePhoto(id, pendingPhoto); notesSource.addFeature(new ol.Feature({ geometry: new ol.geom.Point(coordinate), id: uid(), noteType: "photo", photoId: id, title: pendingPhoto.name || "Bilde", createdAt: new Date().toISOString() })); pendingPhoto = null; $("photo-name").textContent = "Ingen bilde valgt."; $("place-photo").disabled = true; saveData(); toast("Bildet er lagret på kartpunktet."); } catch { toast("Bildet kunne ikke lagres lokalt."); } }
function addText(coordinate) { const body = $("note-text").value.trim(); const title = $("note-title").value.trim(); if (!body && !title) { toast("Skriv litt tekst før du plasserer notatet."); return; } notesSource.addFeature(new ol.Feature({ geometry: new ol.geom.Point(coordinate), id: uid(), noteType: "text", title: title || "Notat", body, createdAt: new Date().toISOString() })); $("note-title").value = ""; $("note-text").value = ""; saveData(); toast("Tekstboksen er lagret på kartpunktet."); }
function addSymbol(coordinate) { if (!pendingSymbol) return; notesSource.addFeature(new ol.Feature({ geometry: new ol.geom.Point(coordinate), id: uid(), noteType: "symbol", symbolType: pendingSymbol.type, title: pendingSymbol.label, body: pendingSymbol.type === "culvert" ? `Diameter: ${pendingSymbol.diameter} mm` : "Kartfestet symbol", diameter: pendingSymbol.diameter || "", createdAt: new Date().toISOString() })); saveData(); toast(`${pendingSymbol.label} er lagret på kartpunktet.`); pendingSymbol = null; }
map.on("singleclick", async (event) => { if (toolMode === "text") { addText(event.coordinate); deactivateTool(); return; } if (toolMode === "photo") { await addPhoto(event.coordinate); deactivateTool(); return; } if (toolMode === "symbol") { addSymbol(event.coordinate); deactivateTool(); return; } let found; map.forEachFeatureAtPixel(event.pixel, (feature, layer) => { if (layer === notesLayer || layer === drawingLayer || layer === importLayer) { found = feature; return true; } }); if (found) showDetail(found); else hideDetail(); });
function hideDetail() { selectedFeature = null; $("detail-card").hidden = true; $("detail-photo").src = ""; }
async function showDetail(feature) { selectedFeature = feature; const type = feature.get("noteType"); $("detail-type").textContent = type === "photo" ? "KARTFESTET BILDE" : type === "text" ? "KARTFESTET NOTAT" : type === "symbol" ? "KARTFESTET SYMBOL" : type === "sketch" ? "SKISSE" : "IMPORTERT SHAPE"; $("detail-title").textContent = feature.get("title") || (type === "sketch" ? "Skisse" : feature.get("sourceName") || "Kartobjekt"); $("detail-body").textContent = feature.get("body") || (type === "sketch" ? "Tegnet i Notatkart." : "Importert shapefil."); const image = $("detail-photo"); image.hidden = true; image.src = ""; if (type === "photo") { const blob = await getPhoto(feature.get("photoId")); if (blob) { image.src = URL.createObjectURL(blob); image.hidden = false; } else $("detail-body").textContent = "Bildefilen finnes ikke lenger lokalt på denne enheten."; } $("detail-card").hidden = false; }
$("delete-object").addEventListener("click", async () => { if (!selectedFeature) return; if (!confirm("Slette dette objektet fra Notatkart?")) return; const photoId = selectedFeature.get("photoId"); [notesSource, drawingSource, importSource].forEach((source) => source.removeFeature(selectedFeature)); if (photoId) await deletePhoto(photoId); saveData(); hideDetail(); toast("Objektet er slettet."); });
$("close-detail").addEventListener("click", hideDetail);
document.querySelectorAll("[data-draw]").forEach((button) => button.addEventListener("click", () => activateDraw(button.dataset.draw)));
$("cancel-tool").addEventListener("click", () => { deactivateTool(); toast("Aktivt verktøy er avsluttet."); });
$("place-text").addEventListener("click", () => selectPlacement("text"));
$("place-culvert").addEventListener("click", () => { const diameter = $("culvert-diameter").value.trim(); if (!diameter || Number(diameter) <= 0) { toast("Skriv inn diameter i millimeter først."); return; } pendingSymbol = { type: "culvert", label: `Stikkrenne Ø ${diameter} mm`, diameter }; selectPlacement("symbol"); });
$("place-landing").addEventListener("click", () => { pendingSymbol = { type: "landing", label: "Velteplass" }; selectPlacement("symbol"); });
$("place-turning").addEventListener("click", () => { pendingSymbol = { type: "turning", label: "Snuplass" }; selectPlacement("symbol"); });
$("photo-input").addEventListener("change", (event) => { pendingPhoto = event.target.files?.[0] || null; $("photo-name").textContent = pendingPhoto ? pendingPhoto.name : "Ingen bilde valgt."; $("place-photo").disabled = !pendingPhoto; });
$("place-photo").addEventListener("click", () => { if (pendingPhoto) selectPlacement("photo"); });
$("base-toggle").addEventListener("change", (event) => { baseLayer.setVisible(event.target.checked); });
$("import-toggle").addEventListener("change", (event) => { importLayer.setVisible(event.target.checked); });
$("notes-toggle").addEventListener("change", (event) => { drawingLayer.setVisible(event.target.checked); notesLayer.setVisible(event.target.checked); });
$("shape-input").addEventListener("change", async (event) => { const file = event.target.files?.[0]; if (!file) return; try { toast("Leser shapefil …"); const parsed = await shp(await file.arrayBuffer()); const collections = parsed.type === "FeatureCollection" ? [parsed] : Object.values(parsed); let total = 0; collections.forEach((collection) => { const features = format.readFeatures(collection, { dataProjection: "EPSG:4326", featureProjection: projection }); features.forEach((feature) => feature.setProperties({ id: uid(), sourceName: file.name, imported: true })); importSource.addFeatures(features); total += features.length; }); saveData(); if (total) { map.getView().fit(importSource.getExtent(), { padding: [70, 280, 70, 280], maxZoom: 16, duration: 500 }); toast(`${total} shapeobjekt er importert og lagret.`); } else toast("Fant ingen geometri i ZIP-filen."); } catch (error) { console.error(error); toast("Kunne ikke importere shapefilen. Kontroller at ZIP-filen inneholder .shp, .shx og .dbf."); } finally { event.target.value = ""; } });
function currentPosition() { if (!navigator.geolocation) { toast("Denne nettleseren støtter ikke posisjon."); return; } $("locate-button").textContent = "Finner posisjon …"; navigator.geolocation.getCurrentPosition((position) => { const coordinate = ol.proj.fromLonLat([position.coords.longitude, position.coords.latitude]); positionSource.clear(); positionSource.addFeature(new ol.Feature(new ol.geom.Point(coordinate))); map.getView().animate({ center: coordinate, zoom: Math.max(map.getView().getZoom(), 16), duration: 600 }); $("locate-button").textContent = "Min posisjon"; if (positionWatch) navigator.geolocation.clearWatch(positionWatch); positionWatch = navigator.geolocation.watchPosition((update) => { positionSource.getFeatures()[0]?.getGeometry().setCoordinates(ol.proj.fromLonLat([update.coords.longitude, update.coords.latitude])); }, () => {}, { enableHighAccuracy: true, maximumAge: 10000 }); toast("Posisjonen vises med blå prikk."); }, () => { $("locate-button").textContent = "Min posisjon"; toast("Fikk ikke posisjon. Kontroller at du har gitt tillatelse."); }, { enableHighAccuracy: true, timeout: 15000 }); }
$("locate-button").addEventListener("click", currentPosition);
function download(blob, filename) { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function exportJpeg() { toast("Lager JPEG av gjeldende kartutsnitt …"); map.once("rendercomplete", () => { try { const size = map.getSize(); const result = document.createElement("canvas"); result.width = size[0]; result.height = size[1]; const context = result.getContext("2d"); Array.from(map.getViewport().querySelectorAll("canvas")).forEach((canvas) => { if (!canvas.width || !canvas.height) return; const opacity = canvas.parentNode.style.opacity || canvas.style.opacity || 1; context.globalAlpha = Number(opacity); const matrix = (canvas.style.transform || "").match(/^matrix\(([^)]+)\)$/); if (matrix) context.setTransform(...matrix[1].split(",").map(Number)); else context.setTransform(1, 0, 0, 1, 0, 0); context.drawImage(canvas, 0, 0); }); context.setTransform(1, 0, 0, 1, 0, 0); result.toBlob((blob) => { if (!blob) throw new Error("Kunne ikke lage bilde"); const stamp = new Date().toISOString().slice(0, 10); download(blob, `notatkart-${stamp}.jpg`); const extent = map.getView().calculateExtent(size); const resolution = map.getView().getResolution(); const worldFile = [resolution, 0, 0, -resolution, extent[0] + resolution / 2, extent[3] - resolution / 2].join("\n"); download(new Blob([worldFile], { type: "text/plain" }), `notatkart-${stamp}.jgw`); download(new Blob(["Koordinatsystem: EPSG:3857 (Web Mercator)\nJPEG og JGW-filen må ligge sammen."], { type: "text/plain" }), `notatkart-${stamp}-lesmeg.txt`); toast("JPEG, JGW og koordinatinfo er lastet ned."); }, "image/jpeg", .92); } catch (error) { console.error(error); toast("Kunne ikke lage JPEG. Prøv igjen når grunnkartet er lastet."); } }); map.renderSync(); }
$("export-button").addEventListener("click", exportJpeg);
loadData();
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js"));
